;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		end-of-buffer
		ignore
		))

(setq mc/cmds-to-run-once
      '(
		helm-buffers-list
		mode-line-previous-buffer
		mouse-drag-mode-line
		smex
		))
